//
//  Emoji.swift
//  Emoji Dictionary
//
//  Created by Justin Storrer on 3/31/21.
//

import Foundation

struct Emoji {
    var character = ""
    var definition = ""
    var year = 0
    var rating = 0.0
    var category = ""
    var description = ""
}

func getEmojis() -> [Emoji] {
    
    let emoji1 = Emoji(character: "🤯", definition: "Exploding Head", year: 2017, rating: 4.6, category: "Face, Unwell", description: "A yellow face with an open mouth, the top of its head exploding in the shape of a brain-like mushroom cloud. A visual form of the expression mind blown, it may represent such emotions as shock, awe, amazement, and disbelief.")
    let emoji2 = Emoji(character: "🤬", definition: "Face with Symbols on Mouth", year: 2017, rating: 3.2, category: "Face, Negative", description: "An angry-red face with a black bar and white grawlixes covering its mouth, indicating it's swearing or being vulgar. Grawlixes are typographical symbols (e.g., @#$%&!) representing swear words or obscenities. Often used to convey an outburst of anger, frustration, or rage.")
    let emoji3 = Emoji(character: "🙃", definition: "Upside-Down Face", year: 2015, rating: 1.2, category: "Face, Smiling", description: "A classic smiley, turned upside down. Implemented as a flipped version of 🙂 Slightly Smiling Face on most platforms. Commonly used to convey irony, sarcasm, joking, or a sense of goofiness or silliness. Its intent can be similar to the bemused Oh well! of 🤷 Person Shrugging or the shruggie emoticon.")
    let emoji4 = Emoji(character: "🌯", definition: "Burrito", year: 2015, rating: 3.7, category: "Food, Prepared", description: "A Mexican or Tex-Mex burrito, featuring a wrapped flour tortilla filled with such ingredients as beef, rice, beans, cheese, tomato, lettuce, and sour cream. Served in foil on several major platforms, suggesting a Mission burrito associated with San Francisco. Not to be confused with the Stuffed Flatbread.")
    let emoji5 = Emoji(character: "👀", definition: "Eyes", year: 2015, rating: 3.2, category: "Body, Parts", description: "A pair of eyes, glancing slightly to the left on most platforms. The Google version of this emoji previously showed only a single eye, despite the name of this character being eyes (plural).")
    let emoji6 = Emoji(character: "💩", definition: "Pile of Poo", year: 2010, rating: 2.6, category: "Face, Costume", description: "A swirl of brown poop, shaped like soft-serve ice cream with large, excited eyes and a big, friendly smile. May be used to represent feces and other bathroom topics as well as stand in for their many related slang terms. It also enjoys a wide range of idiosyncratic applications, such as conveying a sense of whimsy or silliness, given its fun, happy expression.")
    let emoji7 = Emoji(character: "👨‍💻", definition: "Man Technologist", year: 2016, rating: 4.0, category: "Person, Role", description: "A man behind a computer screen, working in the field of technology. The Man Technologist emoji is a ZWJ sequence combining 👨 Man, ‍ Zero Width Joiner and 💻 Laptop. These display as a single emoji on supported platforms.")
    let emoji8 = Emoji(character: "🧠", definition: "Brain", year: 2017, rating: 2.6, category: "Body, Parts", description: "A human brain, shown in pink on most platforms. Used to indicate thinking or the human mind.")
    let emoji9 = Emoji(character: "🤖", definition: "Robot", year: 2015, rating: 4.1, category: "Face, Costume", description: "The head of a classic robot. Commonly depicted as a vintage, tin toy robot with circular eyes, a triangular nose, knobs for ears, a light and/or antennae atop its head, and a grill-like mouth similar to a grimace. Colors vary across platform, but its head is metallic on most platforms. May be used of topics concerning robotics, electronics, computer programming, futurism, and science fiction. It also enjoys a range of idiosyncratic applications, such as conveying a sense of weirdness and fun as well as alarm, surprise, and excitement, given its wide-eyed, teeth-gritting expression.")
    let emoji10 = Emoji(character: "👨‍🚀", definition: "Astronaut", year: 2019, rating: 3.0, category: "Person, Role", description: "The Astronaut emoji is a ZWJ sequence combining 🧑 Person, ‍ Zero Width Joiner and 🚀 Rocket. These display as a single emoji on supported platforms.")
    let emoji11 = Emoji(character: "🏂", definition: "Snowboarder", year: 2010, rating: 2.2, category: "Person, Sport", description: "A person snowboarding downhill at a ski resort. Wearing clothing designed for cold climates.")
    let emoji12 = Emoji(character: "🏍", definition: "Racing Motorcycle", year: 2014, rating: 3.3, category: "Transport, Ground", description: "A motorcycle, otherwise known as a motorbike used for sport/racing purposes. For a transport-based motorcycle, use a motor scooter.")
    let emoji13 = Emoji(character: "🤺", definition: "Person Fencing", year: 2016, rating: 1.7, category: "Person, Sport", description: "A person shown in the sport of fencing, with a Rapier-style sword, mask, and protective clothing.")
    let emoji14 = Emoji(character: "🦅", definition: "Eagle", year: 2016, rating: 4.1, category: "Animal, Bird", description: "A bald eagle, the majestic bird of prey with brown feathers and distinctive white head. Generally depicted facing left, with its wings outspread and talons out, as if swooping down to seize prey.")
    let emoji15 = Emoji(character: "🐉", definition: "Dragon", year: 2015, rating: 4.0, category: "Animal, Reptile", description: "A dragon, a mythical creature resembling a giant reptile found in the folklore of many cultures. Depicted as a green, Chinese-styled dragon in full profile facing left. Generally shown with a curling, snake-like body, clawed feet, yellowish scales on its back, horn-like structures on its head, and whisker-like tendrils by its nostrils.")
    let emoji16 = Emoji(character: "🛼", definition: "Roller Skate", year: 2020, rating: 2.5, category: "Roller Skate", description: "Roller Skate was approved as part of Unicode 13.0 in 2020 and added to Emoji 13.0 in 2020.")
    let emoji17 = Emoji(character: "🛸", definition: "Flying Saucer", year: 2017, rating: 3.6, category: "Transport, Air", description: "A flying saucer, sometimes referred to as an Unidentified Flying Object (UFO). Shown on some platforms with an alien at the controls and/or a beam of light emitting from the base.")
    let emoji18 = Emoji(character: "☄️", definition: "Comet", year: 2015, rating: 4.2, category: "Sky & weather", description: "A comet, an icy, rocky space object that can form a tail of gas and dust when near the sun. Generally depicted as an icy-blue comet, as if streaking downwards in a night sky. May be used for meteors and other celestial bodies, as well as for content concerning space more generally. Also occasionally used for flair or flourish.")
    let emoji19 = Emoji(character: "💎", definition: "Gem Stone", year: 2010, rating: 4.5, category: "Clothing", description: "A jewel or gem, as set into a ring. Depicted in the shape of a classic diamond but in the bright blue color of an aquamarine. Commonly used for various content concerning jewelry, as upon an engagement or marriage. May also convey various literal and figurative senses of beauty, wealth, sophistication, preciousness, and sparkling.")
    let emoji20 = Emoji(character: "🧾", definition: "Receipt", year: 2018, rating: 1.7, category: "Money", description: "A white paper receipt, as proof of payment, and shown flat or curled. May be used for other financial documents (e.g., invoice, tax form). May also be used for the slang receipts, or \"evidence” or “confirmation” of some feat or controversy. Some vendors feature easter eggs. Apple’s design, for instance, displays the date of July 17 (World Emoji Day); items referencing its 1997–2002 Crazy Ones/Think Different ad campaign (misfits, square pegs, round holes); and a balance $0.00.")
    let emoji21 = Emoji(character: "📰", definition: "Newspaper", year: 2010, rating: 3.0, category: "Book, Paper", description: "The front page of a newspaper, as people once read the news before the internet. Commonly used for various content concerning news, media, and journalism as well as personal news. Most platforms depict a nondescript masthead, images, and columns of text. Apple’s newspaper is called The Apple Times, featuring a logo based on its 🦅 Eagle and a picture of its 🌋 Volcano. Facebook’s is called Daily Feed, with a headline “El Capitan” and picture of that famous rock formation in Yosemite National Park. WhatsApp’s paper reads Daily News with a picture of a map.")
    let emoji22 = Emoji(character: "🕹", definition: "Joystick", year: 2014, rating: 4.1, category: "Game", description: "A joystick, as used in playing classic arcade, computer, or video games. Generally depicted with a black base, red-knobbed control stick, and one or more red buttons. Commonly used for content concerning various types of gaming; occasionaly applied to aviation and aircraft.")
    let emoji23 = Emoji(character: "🎰", definition: "Slot Machine", year: 2010, rating: 3.8, category: "Game", description: "A gambling machine generally found in casinos. Shows three wheels with a lever to the side. Most platforms display three 7 digits on this emoji.")
    let emoji24 = Emoji(character: "🎣", definition: "Fishing Pole", year: 2015, rating: 2.7, category: "Sport", description: "A fishing rod (pole) with a fish caught on the end.")
    
    return [emoji1, emoji2, emoji3, emoji4, emoji5, emoji6, emoji7, emoji8, emoji9, emoji10, emoji11, emoji12, emoji13, emoji14, emoji15, emoji16, emoji17, emoji18, emoji19, emoji20, emoji21, emoji22, emoji23, emoji24]
}
